//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Connect
    {
        public int Kod_connectoin { get; set; }
        public int Kod_entry { get; set; }
        public int Kod_services { get; set; }
    
        public virtual Entry Entry { get; set; }
        public virtual Services Services { get; set; }
    }
}
