//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Connect> Connect { get; set; }
        public virtual DbSet<Dolgnosti> Dolgnosti { get; set; }
        public virtual DbSet<Entry> Entry { get; set; }
        public virtual DbSet<Genders> Genders { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<Services_dolgnosti> Services_dolgnosti { get; set; }
        public virtual DbSet<Specialists> Specialists { get; set; }
    }
}
