//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo
    {
        public int Kod_photo { get; set; }
        public int Kod_clients { get; set; }
        public string PhotoPath { get; set; }
        public byte[] PhotoBinary { get; set; }
    
        public virtual Clients Clients { get; set; }
    }
}
